name: Atualizar Ranking e Guild (Diário)

on:
  schedule:
    # Roda todos os dias às 09:00 UTC (06:00 Brasil)
    - cron: '47 8 * * *'
  workflow_dispatch: # Permite rodar manualmente para testar

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write  # Necessário para salvar o CSV no Git
      id-token: write  # OBRIGATÓRIO para a autenticação do Google funcionar

    steps:
    - name: Baixar código do repositório
      uses: actions/checkout@v4

    # Autenticação configurada com a versão estável para Node 24
    - name: Autenticar no Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    # Atualizado para v5 para evitar o erro de depreciação do Node 20
    - name: Instalar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip' # Otimiza o tempo de execução salvando as bibliotecas

    - name: Instalar bibliotecas
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Rodar script de extração (Ranking)
      run: python extrair_ranking.py

    - name: Rodar Extração de Guild
      run: python etl_guild.py

    - name: Salvar e Enviar Arquivo (Commit & Push)
      run: |
        git config --global user.name 'GitHub Action Bot'
        git config --global user.email 'action@github.com'
        git add dados/
        git commit -m "Atualizacao diaria dos dados [skip ci]" || echo "Sem mudanças no ranking para salvar"
        git push
